cont_thres: 8
counter_window_period: 500
df_a: 8
df_arrangement: Absolute
df_g: 17
df_h: 4
five_hop_percentage: 100
g_vc_buf_size: 256
gl_file: topology/4_8_17_topo.conf
global_latency: 15
injection_rate: 0.61
injection_rate_uses_flits: 1
internal_speedup: 2.5
l_vc_buf_size: 256
learning_rate: 0.001
local_latency: 10
max_samples: 10
num_vcs: 4
packet_size: 1
parallel_links: 2
routing_delay: 0
routing_function: UGAL_L
sample_period: 10000
sw_allocator: separable_input_first
t_vc_buf_size: 256
topology: dragonflyfull
traffic: from_file
traffic_file: /nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/uniform
ugal_bias: 0
ugal_l_mode: 0
ugal_multiply_mode: pathlen_based
ur_thres: 10
vc_allocation_mode: dally
vc_allocator: separable_input_first
warmup_periods: 3
