#topology
topology :  dragonflyfull
df_a : 8
df_g : 17
df_h : 4
gl_file : topology/4_8_17_topo.conf
df_arrangement : Absolute
parallel_links : 2
counter_window_period : 500

#Router config
vc_allocator :  separable_input_first
sw_allocator :  separable_input_first
routing_delay  :  0
global_latency : 15
local_latency : 10
internal_speedup  :  2.5
l_vc_buf_size :  256
g_vc_buf_size :  256
t_vc_buf_size : 256

#simulation config
warmup_periods :  3
sample_period  :  10000
max_samples : 10
packet_size :  1
injection_rate_uses_flits: 1
injection_rate :  0.61

#Routing config
#MIN, VAL, UGAL_G, PAR, UGAL_L
routing_function :  UGAL_L
num_vcs     :  4
vc_allocation_mode :  dally
five_hop_percentage : 100
ugal_multiply_mode : pathlen_based
ugal_l_mode : 0
ugal_bias : 0
cont_thres : 8
learning_rate: 0.001
ur_thres: 10


#Traffic config

traffic_file : /nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/uniform
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/shift]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/pemixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/pemixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/pemixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/permmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/permmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/permmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/rbmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/rbmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/rbmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/17G_perm_patterns/randperm]

# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/uniform]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/shift]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/pemixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/pemixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/pemixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/permmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/permmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/permmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/rbmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/rbmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/rbmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/27G_perm_patterns/randperm]



# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/uniform]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/shift]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/pemixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/pemixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/pemixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/permmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/permmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/permmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/rbmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/rbmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/rbmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/randperm1]

# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/randperm2]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/randperm3]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/randperm4]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim_driver/9G_484_perm_patterns/randperm5]


# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/shift]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/uniform]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/pemixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/pemixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/pemixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/permmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/permmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/permmixed-75]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/randperm1]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/rbmixed-25]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/rbmixed-50]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/rbmixed-75]


# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/randperm2]
# traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/33G_perm_patterns/randperm5]




# traffic_file : [/nfsdata/ram/summer_2021/Booksim_congestion_study/src_congestion_study/traffic_patterns/9G_rand_perm]
#traffic_file : [/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/shift,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/rbmixed-25,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/rbmixed-50,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/rbmixed-75,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/pemixed-25,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/pemixed-50,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/pemixed-75,/nfsdata/ram/run_sim_test/sim/sim-004/9G_perm_patterns/randperm1]
traffic       :  from_file

#Data Collection
